---
site:
  title: ARO HCP Sandbox Workshop
  url: https://rhpds.github.io/aro-hcp-sandbox-workshop
  start_page: modules::index.adoc

content:
  sources:
    - url: .
      start_path: content

ui:
  bundle:
    url: https://github.com/rhpds/rhdp_showroom_theme/releases/download/v2.0.3/ui-bundle.zip
    snapshot: true

antora:
  extensions:
    - require: '@andrew-jones/antora-tabs-extension'

output:
  dir: ./www
