---
type: showroom

default_width: 30
persist_url_state: true

view_switcher:
  enabled: true
  default_mode: split

tabs:
  - name: ">_ terminal-1"
    path: /wetty
    port: 443
  - name: ">_ terminal-2"
    path: /wetty
    port: 443
  
